export const ARCHIVE_SPORTS = [
  { id: "ice_hockey", name: "Ishockey", icon: "🏒", blurb: "Svenska guldnätter och klassiker mellan landslag." },
  { id: "football", name: "Fotboll", icon: "⚽", blurb: "Skrällar, derbyn och stora turneringar." },
  { id: "boxing", name: "Boxning", icon: "🥊", blurb: "Tungviktsnätter, revanscher och delade domslut." },
  { id: "tennis", name: "Tennis", icon: "🎾", blurb: "Grus, gräs och maraton i fem set." },
  { id: "athletics", name: "Friidrott", icon: "🏃", blurb: "Banor, hopp och rekord under tak." },
  { id: "equestrian", name: "Ridsport", icon: "🏇", blurb: "Hoppningar och dressyrprogram från de stora spelen." },
  { id: "handball", name: "Handboll", icon: "🤾", blurb: "Svenska hallklassiker och sena avgöranden." },
] as const;

export type ArchiveSportId = (typeof ARCHIVE_SPORTS)[number]["id"];

export interface ArchiveSportFixture {
  id: string;
  sport: ArchiveSportId;
  title: string;
  year: number;
  context: string;
  difficulty: 1 | 2 | 3;
  clueCount: number;
}

/** Public case names only. Match ids open in the daily solver. */
export const ARCHIVE_FIXTURES: ArchiveSportFixture[] = [
  {
    id: "sverige-sovjet-1984",
    sport: "ice_hockey",
    title: "Klassisk drabbning i Scandinavium",
    year: 1984,
    context: "Internationell klassiker",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "slaget-i-sudden",
    sport: "ice_hockey",
    title: "Mysteriet på isen #1",
    year: 2015,
    context: "Slutspelsdrama",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "guldkampen-i-norr",
    sport: "ice_hockey",
    title: "Mysteriet på isen #2",
    year: 2013,
    context: "Finalserie",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "miracle-on-ice-1980",
    sport: "ice_hockey",
    title: "Sirenen i kylan",
    year: 1980,
    context: "OS-semifinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "summit-series-1972",
    sport: "ice_hockey",
    title: "Sirenen före midnatt",
    year: 1972,
    context: "Landslagsserie",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "turin-gold-2006",
    sport: "ice_hockey",
    title: "Vintermorgonen i alperna",
    year: 2006,
    context: "Mästerskapsfinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "farjestad-skelleftea-2011",
    sport: "ice_hockey",
    title: "Mysteriet på isen #3",
    year: 2011,
    context: "Guldnatt när hemmaplan sjunger",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "brynas-skelleftea-2012",
    sport: "ice_hockey",
    title: "Mysteriet på isen #4",
    year: 2012,
    context: "Jubileumsguld i sista matchen",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "skelleftea-farjestad-2014",
    sport: "ice_hockey",
    title: "Mysteriet på isen #5",
    year: 2014,
    context: "Finalsvep utan en enda retur",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "frolunda-skelleftea-2016",
    sport: "ice_hockey",
    title: "Mysteriet på isen #6",
    year: 2016,
    context: "Bortaguld efter lång väntan",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "montevideo-1930",
    sport: "football",
    title: "Natten på Centenario",
    year: 1930,
    context: "VM-final",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "bern-1954",
    sport: "football",
    title: "Radiosändningen från Bern",
    year: 1954,
    context: "VM-final",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "pele-sweden-1958",
    sport: "football",
    title: "Genombrottet på värdarnas plan",
    year: 1958,
    context: "Världsmästerskapet",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "hurst-1966",
    sport: "football",
    title: "Ribban i förlängningen",
    year: 1966,
    context: "VM-final",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "hand-of-god-1986",
    sport: "football",
    title: "Två ögonblick på hög höjd",
    year: 1986,
    context: "Utslagsmatch",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "pasadena-bronze-1994",
    sport: "football",
    title: "Sommarnatten i västern",
    year: 1994,
    context: "Världsmästerskapet",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "sondagsmorgonen-stockholms-stad",
    sport: "football",
    title: "Mysteriet på gräset #1",
    year: 2018,
    context: "Derbyklassiker",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "guldstriden-sista-omgangen",
    sport: "football",
    title: "Mysteriet på gräset #2",
    year: 2007,
    context: "Guldstrid",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "aik-djurgarden-2017",
    sport: "football",
    title: "Mysteriet på gräset #3",
    year: 2017,
    context: "Tvillingderby som väger jämnt",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "malmo-ifk-2015",
    sport: "football",
    title: "Mysteriet på gräset #4",
    year: 2015,
    context: "Rivalmöte i toppstriden",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "elfsborg-djurgarden-2006",
    sport: "football",
    title: "Mysteriet på gräset #5",
    year: 2006,
    context: "Guld efter en hel generation",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "hammarby-aik-2016",
    sport: "football",
    title: "Mysteriet på gräset #6",
    year: 2016,
    context: "Derby avgjort före paus",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "united-1999",
    sport: "football",
    title: "Natten på tilläggstid",
    year: 1999,
    context: "Europacupfinal",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "chastain-1999",
    sport: "football",
    title: "Straffen på Rose Bowl",
    year: 1999,
    context: "VM-final",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "leicester-2016",
    sport: "football",
    title: "Den oprissatta titeln",
    year: 2016,
    context: "Ligasejour",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "messi-2022",
    sport: "football",
    title: "Den förgyllda straffläggningen",
    year: 2022,
    context: "VM-final",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "rumble-in-the-jungle-1974",
    sport: "boxing",
    title: "Natten före gryningen",
    year: 1974,
    context: "Titelmatch",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "king-1973",
    sport: "tennis",
    title: "Uppvisningen i Houston",
    year: 1973,
    context: "Uppvisningsmatch",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "wimbledon-epic-1980",
    sport: "tennis",
    title: "Setet som inte ville sluta",
    year: 1980,
    context: "Gräsfinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "owens-1936",
    sport: "athletics",
    title: "Banorna i Berlin",
    year: 1936,
    context: "OS-sprint",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "fosbury-1968",
    sport: "athletics",
    title: "Ribban baklänges",
    year: 1968,
    context: "OS-höjdhopp",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "bolt-beijing-2008",
    sport: "athletics",
    title: "Spikarna före bandet",
    year: 2008,
    context: "Kort banfinal",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "super-saturday-2012",
    sport: "athletics",
    title: "Natten i London",
    year: 2012,
    context: "OS-finaler",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "duplantis-2026",
    sport: "athletics",
    title: "Ribban som höjdes",
    year: 2026,
    context: "Inomhusrekord",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "tyson-holyfield-1996",
    sport: "boxing",
    title: "Natten i öknen",
    year: 1996,
    context: "Titelmatch",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "thrilla-manila-1975",
    sport: "boxing",
    title: "Hettan i huvudstaden",
    year: 1975,
    context: "Titelmatch",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "clay-liston-1964",
    sport: "boxing",
    title: "Kvällen då namnet väntade",
    year: 1964,
    context: "Titelmatch",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "hagler-leonard-1987",
    sport: "boxing",
    title: "Korten som inte enades",
    year: 1987,
    context: "Titelmatch",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "louis-schmeling-1938",
    sport: "boxing",
    title: "Revanchen före pausen",
    year: 1938,
    context: "Titelmatch",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "federer-nadal-2008",
    sport: "tennis",
    title: "Skymningen på gräset",
    year: 2008,
    context: "Gräsfinal",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "borg-mcenroe-1981",
    sport: "tennis",
    title: "Svitens sista final",
    year: 1981,
    context: "Gräsfinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "edberg-becker-1988",
    sport: "tennis",
    title: "Måndagen efter regnet",
    year: 1988,
    context: "Gräsfinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "wilander-1982",
    sport: "tennis",
    title: "Tonåringen på gruset",
    year: 1982,
    context: "Grusfinal",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "saint-cyr-1956",
    sport: "equestrian",
    title: "Sommaren som flyttades",
    year: 1956,
    context: "Olympisk dressyr",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "tokyo-hopp-2021",
    sport: "equestrian",
    title: "Klockan över bommarna",
    year: 2021,
    context: "Laghoppning",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "dujardin-2012",
    sport: "equestrian",
    title: "Musiken i parken",
    year: 2012,
    context: "Fristil",
    difficulty: 1,
    clueCount: 5,
  },
  {
    id: "handboll-vm-1999",
    sport: "handball",
    title: "Underläget i hettan",
    year: 1999,
    context: "VM-final",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "handboll-em-1994",
    sport: "handball",
    title: "Den första europeiska kvällen",
    year: 1994,
    context: "EM-final",
    difficulty: 2,
    clueCount: 5,
  },
  {
    id: "handboll-em-2022",
    sport: "handball",
    title: "Straffen efter signalen",
    year: 2022,
    context: "EM-final",
    difficulty: 1,
    clueCount: 5,
  },
];

export function archiveSportFromParam(value: string | undefined | null): ArchiveSportId {
  const match = ARCHIVE_SPORTS.find((sport) => sport.id === value);
  return match?.id ?? "ice_hockey";
}

export function loadArchiveIndex(sport: string | undefined | null = "ice_hockey"): ArchiveSportFixture[] {
  const selected = archiveSportFromParam(sport);
  return ARCHIVE_FIXTURES.filter((fixture) => fixture.sport === selected);
}

export function deduceHref(fixtureId: string): string {
  return `/play/${encodeURIComponent(fixtureId)}`;
}
