/** Spoiler-safe titles. Answer strings live only in `options`. */
export interface KluringMeta {
  title: { sv: string; en: string };
  category: { sv: string; en: string };
  year: number;
  options: readonly [string, string, string, string];
  correctAnswerIndex: 0 | 1 | 2 | 3;
}

export const KLURING_META: Record<string, KluringMeta> = {
  "sverige-sovjet-1984": {
    title: { sv: "Höstmötet i väst", en: "The autumn meeting out west" },
    category: { sv: "Kanada Cup", en: "Canada Cup" },
    year: 1984,
    options: [
      "1981 OS-hockey: Sverige mot Sovjetunionen",
      "1984 Kanada Cup: Sverige mot Sovjetunionen",
      "1976 OS-hockey: Sverige mot Tjeckoslovakien",
      "1984 OS-hockey: Sverige mot Finland",
    ],
    correctAnswerIndex: 1,
  },
  "miracle-1980": {
    title: { sv: "Det frusna undret", en: "The frozen miracle" },
    category: { sv: "Olympisk medaljomgång", en: "Olympic medal round" },
    year: 1980,
    options: [
      "1980 OS-hockey: USA mot Sovjetunionen",
      "1980 OS-hockey: Sverige mot Sovjetunionen",
      "1976 OS-hockey: Kanada mot Sovjetunionen",
      "1984 OS-hockey: USA mot Kanada",
    ],
    correctAnswerIndex: 0,
  },
  "summit-series-1972": {
    title: { sv: "Den åttonde sirenen", en: "The eighth siren" },
    category: { sv: "Summitseriens avgörande", en: "Summit Series decider" },
    year: 1972,
    options: [
      "1976 OS-hockey: Kanada mot Tjeckoslovakien",
      "1972 OS-hockey: Sverige mot Sovjetunionen",
      "1972 Summitserien: Kanada mot Sovjetunionen",
      "1980 OS-hockey: USA mot Sovjetunionen",
    ],
    correctAnswerIndex: 2,
  },
  "turin-gold-2006": {
    title: { sv: "Guldet i den nya hallen", en: "Gold in the new rink" },
    category: { sv: "Olympisk final", en: "Olympic final" },
    year: 2006,
    options: [
      "1994 OS-hockey: Sverige mot Kanada",
      "2006 OS-hockey: Kanada mot USA",
      "2010 OS-hockey: USA mot Kanada",
      "2006 OS-hockey: Sverige mot Finland",
    ],
    correctAnswerIndex: 3,
  },
  "lillehammer-1994": {
    title: { sv: "Bilden på frimärket", en: "The picture on the stamp" },
    category: { sv: "Olympisk final", en: "Olympic final" },
    year: 1994,
    options: [
      "1994 OS-hockey: Sverige mot Kanada",
      "2006 OS-hockey: Sverige mot Finland",
      "1980 OS-hockey: USA mot Sovjetunionen",
      "1998 OS-hockey: Kanada mot USA",
    ],
    correctAnswerIndex: 0,
  },
  "skelleftea-guld-2013": {
    title: { sv: "Nollan i norr", en: "The shutout in the north" },
    category: { sv: "SM-final", en: "Swedish final" },
    year: 2013,
    options: [
      "2012 SM-final: Brynäs mot Skellefteå",
      "2013 SM-final: Skellefteå mot Luleå",
      "2014 SM-final: Färjestad mot Luleå",
      "2008 SM-final: HV71 mot Linköping",
    ],
    correctAnswerIndex: 1,
  },
  "pele-1958": {
    title: { sv: "Genombrottet i Solna", en: "The Solna breakthrough" },
    category: { sv: "VM-final", en: "World Cup final" },
    year: 1958,
    options: [
      "1950 VM-final: Uruguay mot Brasilien",
      "1954 VM-final: Västtyskland mot Ungern",
      "1958 VM-final: Brasilien mot Sverige",
      "1962 VM-final: Brasilien mot Tjeckoslovakien",
    ],
    correctAnswerIndex: 2,
  },
  "maradona-1986": {
    title: { sv: "Dubbeln på Azteca", en: "The Azteca double" },
    category: { sv: "VM-kvartsfinal", en: "World Cup quarter-final" },
    year: 1986,
    options: [
      "1986 VM-kvartsfinal: Argentina mot England",
      "1986 VM-final: Argentina mot Västtyskland",
      "1978 VM-final: Argentina mot Nederländerna",
      "1990 VM-final: Västtyskland mot Argentina",
    ],
    correctAnswerIndex: 0,
  },
  "hurst-1966": {
    title: { sv: "Ribban på hemmaplan", en: "The crossbar at home" },
    category: { sv: "VM-final", en: "World Cup final" },
    year: 1966,
    options: [
      "1954 VM-final: Västtyskland mot Ungern",
      "1966 VM-final: England mot Västtyskland",
      "1974 VM-final: Västtyskland mot Nederländerna",
      "1966 VM-final: England mot Portugal",
    ],
    correctAnswerIndex: 1,
  },
  "bern-1954": {
    title: { sv: "Rösten i radion", en: "The voice on the radio" },
    category: { sv: "VM-final", en: "World Cup final" },
    year: 1954,
    options: [
      "1950 VM-final: Uruguay mot Brasilien",
      "1958 VM-final: Brasilien mot Sverige",
      "1966 VM-final: England mot Västtyskland",
      "1954 VM-final: Västtyskland mot Ungern",
    ],
    correctAnswerIndex: 3,
  },
  "messi-2022": {
    title: { sv: "Natten under taket", en: "The night under the roof" },
    category: { sv: "VM-final", en: "World Cup final" },
    year: 2022,
    options: [
      "2014 VM-final: Tyskland mot Argentina",
      "2018 VM-final: Frankrike mot Kroatien",
      "2022 VM-final: Argentina mot Frankrike",
      "2006 VM-final: Italien mot Frankrike",
    ],
    correctAnswerIndex: 2,
  },
  "ali-1974": {
    title: { sv: "Natten i Kinshasa", en: "The Kinshasa night" },
    category: { sv: "Tungviktstitel", en: "Heavyweight title" },
    year: 1974,
    options: [
      "1974 Tungviktstitel: Ali mot Foreman",
      "1975 Tungviktstitel: Ali mot Frazier",
      "1971 Tungviktstitel: Frazier mot Ali",
      "1978 Tungviktstitel: Ali mot Spinks",
    ],
    correctAnswerIndex: 0,
  },
  "tyson-holyfield-1996": {
    title: { sv: "Elfte ronden i öknen", en: "The eleventh round in the desert" },
    category: { sv: "Tungviktstitel", en: "Heavyweight title" },
    year: 1996,
    options: [
      "1990 Tungviktstitel: Tyson mot Douglas",
      "1996 Tungviktstitel: Holyfield mot Tyson",
      "1997 Tungviktstitel: Tyson mot Holyfield",
      "1988 Tungviktstitel: Tyson mot Spinks",
    ],
    correctAnswerIndex: 1,
  },
  "thrilla-manila-1975": {
    title: { sv: "Hettan i tredje mötet", en: "Heat in the third meeting" },
    category: { sv: "Tungviktstitel", en: "Heavyweight title" },
    year: 1975,
    options: [
      "1971 Tungviktstitel: Frazier mot Ali",
      "1974 Tungviktstitel: Ali mot Foreman",
      "1975 Tungviktstitel: Ali mot Frazier",
      "1964 Tungviktstitel: Clay mot Liston",
    ],
    correctAnswerIndex: 2,
  },
  "clay-liston-1964": {
    title: { sv: "Pallen i strandstaden", en: "The stool in the beach city" },
    category: { sv: "Tungviktstitel", en: "Heavyweight title" },
    year: 1964,
    options: [
      "1965 Tungviktstitel: Ali mot Liston",
      "1962 Tungviktstitel: Liston mot Patterson",
      "1967 Tungviktstitel: Ali mot Terrell",
      "1964 Tungviktstitel: Clay mot Liston",
    ],
    correctAnswerIndex: 3,
  },
  "hagler-leonard-1987": {
    title: { sv: "Korten vid kasinot", en: "The cards by the casino" },
    category: { sv: "Mellanvikt", en: "Middleweight" },
    year: 1987,
    options: [
      "1987 Mellanvikt: Leonard mot Hagler",
      "1980 Mellanvikt: Hagler mot Minter",
      "1985 Mellanvikt: Hagler mot Hearns",
      "1987 Mellanvikt: Hagler mot Leonard",
    ],
    correctAnswerIndex: 0,
  },
  "wimbledon-epic-1980": {
    title: { sv: "Avgörandet som inte tog slut", en: "The decider that would not end" },
    category: { sv: "Wimbledonfinal", en: "Wimbledon final" },
    year: 1980,
    options: [
      "1981 Wimbledonfinal: McEnroe mot Borg",
      "1980 Wimbledonfinal: Borg mot McEnroe",
      "1979 Wimbledonfinal: Borg mot Connors",
      "1980 Wimbledonfinal: McEnroe mot Connors",
    ],
    correctAnswerIndex: 1,
  },
  "federer-nadal-2008": {
    title: { sv: "Skymningen på gräset", en: "Dusk on the grass" },
    category: { sv: "Wimbledonfinal", en: "Wimbledon final" },
    year: 2008,
    options: [
      "2007 Wimbledonfinal: Federer mot Nadal",
      "2006 Wimbledonfinal: Federer mot Nadal",
      "2008 Wimbledonfinal: Nadal mot Federer",
      "2009 Wimbledonfinal: Federer mot Roddick",
    ],
    correctAnswerIndex: 2,
  },
  "borg-mcenroe-1981": {
    title: { sv: "Slutet på sviten", en: "The end of the run" },
    category: { sv: "Wimbledonfinal", en: "Wimbledon final" },
    year: 1981,
    options: [
      "1981 Wimbledonfinal: McEnroe mot Borg",
      "1980 Wimbledonfinal: Borg mot McEnroe",
      "1982 Wimbledonfinal: Connors mot McEnroe",
      "1978 Wimbledonfinal: Borg mot Connors",
    ],
    correctAnswerIndex: 0,
  },
  "edberg-becker-1988": {
    title: { sv: "Måndagen efter regnet", en: "The Monday after the rain" },
    category: { sv: "Wimbledonfinal", en: "Wimbledon final" },
    year: 1988,
    options: [
      "1985 Wimbledonfinal: Becker mot Curren",
      "1989 Wimbledonfinal: Becker mot Edberg",
      "1990 Wimbledonfinal: Edberg mot Becker",
      "1988 Wimbledonfinal: Edberg mot Becker",
    ],
    correctAnswerIndex: 3,
  },
  "king-1973": {
    title: { sv: "Kvällen under kupolen", en: "The night under the dome" },
    category: { sv: "Inomhusfinal", en: "Indoor final" },
    year: 1973,
    options: [
      "1973 Wimbledonfinal: King mot Court",
      "1973 Inomhusfinal: King mot Riggs",
      "1975 Inomhusfinal: King mot Evert",
      "1973 Inomhusfinal: Riggs mot Court",
    ],
    correctAnswerIndex: 1,
  },
  "duplantis-2026": {
    title: { sv: "Ribban under taket", en: "The bar under the roof" },
    category: { sv: "Stavhopp", en: "Pole vault" },
    year: 2026,
    options: [
      "2026 Stavhopp: Duplantis 6,31",
      "2024 Stavhopp: Duplantis 6,24",
      "2022 Stavhopp: Duplantis 6,21",
      "2020 Stavhopp: Duplantis 6,18",
    ],
    correctAnswerIndex: 0,
  },
  "owens-1936": {
    title: { sv: "Fyra finaler", en: "Four finals" },
    category: { sv: "Olympiska spel", en: "Olympic Games" },
    year: 1936,
    options: [
      "1932 Olympiska spel: Tolan på 100 meter",
      "1984 Olympiska spel: Lewis fyra guld",
      "1936 Olympiska spel: Jesse Owens fyra guld i Berlin",
      "1960 Olympiska spel: Berruti på 200 meter",
    ],
    correctAnswerIndex: 2,
  },
  "fosbury-1968": {
    title: { sv: "Ryggen mot ribban", en: "Back to the bar" },
    category: { sv: "Olympiska spel", en: "Olympic Games" },
    year: 1968,
    options: [
      "1964 Olympiska spel: Brumel i höjd",
      "1968 Olympiska spel: Dick Fosbury och ryggfloppen",
      "1972 Olympiska spel: Tarmak i höjd",
      "1980 Olympiska spel: Wszola i höjd",
    ],
    correctAnswerIndex: 1,
  },
  "saint-cyr-1956": {
    title: { sv: "Programmet som blev kvar", en: "The program that remained" },
    category: { sv: "Dressyr", en: "Dressage" },
    year: 1956,
    options: [
      "1952 Dressyr: Saint Cyr",
      "1960 Dressyr: Filatov",
      "1948 Dressyr: Moser",
      "1956 Dressyr: Saint Cyr",
    ],
    correctAnswerIndex: 3,
  },
  "tokyo-hopp-2021": {
    title: { sv: "Klockan i omhoppningen", en: "The clock in the jump-off" },
    category: { sv: "OS-hoppning", en: "Olympic show jumping" },
    year: 2021,
    options: [
      "2021 OS-hoppning: Sverige mot USA",
      "2016 OS-hoppning: Frankrike mot USA",
      "2012 OS-hoppning: Storbritannien mot Nederländerna",
      "2008 OS-hoppning: Kanada mot USA",
    ],
    correctAnswerIndex: 0,
  },
  "dujardin-2012": {
    title: { sv: "Musiken i parken", en: "The music in the park" },
    category: { sv: "Dressyr", en: "Dressage" },
    year: 2012,
    options: [
      "2008 Dressyr: Anky",
      "2016 Dressyr: Dujardin",
      "2012 Dressyr: Dujardin",
      "2004 Dressyr: Werth",
    ],
    correctAnswerIndex: 2,
  },
  "handboll-vm-1999": {
    title: { sv: "Ett mål i hettan", en: "One goal in the heat" },
    category: { sv: "VM-final", en: "World Cup final" },
    year: 1999,
    options: [
      "1990 VM-final: Sverige mot Sovjetunionen",
      "1999 VM-final: Sverige mot Ryssland",
      "2001 VM-final: Frankrike mot Sverige",
      "1999 VM-final: Ryssland mot Spanien",
    ],
    correctAnswerIndex: 1,
  },
  "handboll-em-1994": {
    title: { sv: "Det första europaguldet", en: "The first European gold" },
    category: { sv: "EM-final", en: "European Championship final" },
    year: 1994,
    options: [
      "1994 EM-final: Sverige mot Ryssland",
      "1998 EM-final: Sverige mot Spanien",
      "2002 EM-final: Sverige mot Tyskland",
      "1994 EM-final: Ryssland mot Frankrike",
    ],
    correctAnswerIndex: 0,
  },
  "handboll-em-2022": {
    title: { sv: "Straffen efter signalen", en: "The penalty after the signal" },
    category: { sv: "EM-final", en: "European Championship final" },
    year: 2022,
    options: [
      "2020 EM-final: Spanien mot Kroatien",
      "2018 EM-final: Spanien mot Sverige",
      "2024 EM-final: Frankrike mot Sverige",
      "2022 EM-final: Sverige mot Spanien",
    ],
    correctAnswerIndex: 3,
  },
};
