/** Turns short English labels and matchup options into Swedish. Idempotent on Swedish text. */
const REPLACEMENTS: Array<[RegExp, string]> = [
  [/Olympic Hockey/gi, "OS-hockey"],
  [/Olympic Basketball/gi, "OS-basket"],
  [/Olympic Medal Round/gi, "Olympisk medaljomgång"],
  [/Olympic All-Around/gi, "Olympisk mångkamp"],
  [/Olympic Gold-Medal Game/gi, "Olympisk final"],
  [/Olympic 100m Final/gi, "Olympisk 100-metersfinal"],
  [/Olympic Games/gi, "Olympiska spel"],
  [/Olympics/gi, "OS"],
  [/Heavyweight Title Fight/gi, "Tungviktstitel"],
  [/Summit Series Decider/gi, "Summitseriens avgörande"],
  [/Summit Series/gi, "Summitserien"],
  [/World Cup Quarter-Final/gi, "VM-kvartsfinal"],
  [/World Cup Final/gi, "VM-final"],
  [/World Cup/gi, "VM"],
  [/Wimbledon Gentlemen's Final/gi, "Wimbledonfinal"],
  [/Gentlemen's Final/gi, "herrfinal"],
  [/Ice Hockey/gi, "Ishockey"],
  [/Ice hockey/g, "Ishockey"],
  [/Soviet Union/gi, "Sovjetunionen"],
  [/Czechoslovakia/gi, "Tjeckoslovakien"],
  [/West Germany/gi, "Västtyskland"],
  [/East Germany/gi, "Östtyskland"],
  [/South Africa/gi, "Sydafrika"],
  [/New Zealand/gi, "Nya Zeeland"],
  [/Bayern Munich/gi, "Bayern München"],
  [/Netherlands/gi, "Nederländerna"],
  [/Yugoslavia/gi, "Jugoslavien"],
  [/Hungary/gi, "Ungern"],
  [/Croatia/gi, "Kroatien"],
  [/Brazil/gi, "Brasilien"],
  [/Sweden/gi, "Sverige"],
  [/Canada/gi, "Kanada"],
  [/Italy/gi, "Italien"],
  [/France/gi, "Frankrike"],
  [/Spain/gi, "Spanien"],
  [/China/gi, "Kina"],
  [/Football/g, "Fotboll"],
  [/Boxing/g, "Boxning"],
  [/Basketball/g, "Basket"],
  [/Athletics/g, "Friidrott"],
  [/Gymnastics/g, "Gymnastik"],
  [/The favorite/g, "Favoriten"],
  [/the defending champion/g, "den regerande mästaren"],
  [/The record holder/g, "Rekordhållaren"],
  [/the lane-four challenger/g, "utmanaren i bana fyra"],
  [/The host-nation runner/g, "Hemmanationens löpare"],
  [/the Olympic champion/g, "den olympiska mästaren"],
  [/The defending champion/g, "Den regerande mästaren"],
  [/the home favorite/g, "hemmafavoriten"],
  [/The Soviet entry/g, "Det sovjetiska bidraget"],
  [/the Romanian entry/g, "det rumänska bidraget"],
  [/The all-around leader/g, "Ledaren i mångkampen"],
  [/the vault specialist/g, "hoppspecialisten"],
  [/The hosts/g, "Hemmalaget"],
  [/the visitors/g, "bortalaget"],
  [/The holders/g, "Regerande mästare"],
  [/the challengers/g, "utmanarna"],
  [/The favorites/g, "Favoriterna"],
  [/the underdogs/g, "utmanarna"],
  [/\bFixture\b/g, "Match"],
  [/\bvs\.?\b/gi, "mot"],
];

export function swedishSurface(value: string): string {
  return REPLACEMENTS.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}
